# 스포츠 목록 등록

INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('축구', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('농구', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('야구', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('배구', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('테니스', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('탁구', NOW(), NOW());
INSERT INTO SportEvent (`name`, `created_at`, `updated_at`) VALUES ('풋살', NOW(), NOW());

# 대학교 목록 등록

INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭대학교 성신교정 (이원화캠퍼스)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭대학교 서울 종로 (이원화캠퍼스)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강서대학교 서울캠퍼스 (본교)', '서울 강서', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('건국대학교 서울캠퍼스 (본교)', '서울 광진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경기대학교 서울캠퍼스 (이원화캠퍼스)', '서울 서대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경희대학교 서울캠퍼스 (본교)', '서울 동대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고려대학교 서울캠퍼스 (본교)', '서울 성북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광운대학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('국민대학교 북악캠퍼스 (본교)', '서울 성북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동국대학교 서울캠퍼스 (본교)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('명지대학교 인문캠퍼스 (이원화캠퍼스)', '서울 마포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('삼육대학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('상명대학교 서울캠퍼스 (본교)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서강대학교 서울캠퍼스 (본교)', '서울 마포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서경대학교 서울캠퍼스 (본교)', '서울 성북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울대학교 관악캠퍼스 (본교)', '서울 관악', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울대학교 서울 종로 (이원화캠퍼스)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울과학기술대학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울시립대학교 전농캠퍼스 (본교)', '서울 동대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성공회대학교 서울캠퍼스 (본교)', '서울 구로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성균관대학교 인문사회캠퍼스 (이원화캠퍼스)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('세종대학교 서울캠퍼스 (본교)', '서울 강동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('숭실대학교 서울캠퍼스 (본교)', '서울 동작', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연세대학교 신촌캠퍼스 (본교)', '서울 서대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중앙대학교 서울캠퍼스 (본교)', '서울 동작', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중앙대학교 서울 종로 (본교)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('총신대학교 사당캠퍼스 (본교)', '서울 동작', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국외국어대학교 서울캠퍼스 (이원화캠퍼스)', '서울 동대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한성대학교 서울캠퍼스 (본교)', '서울 성북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한양대학교 서울캠퍼스 (본교)', '서울 성동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('홍익대학교 서울캠퍼스 (본교)', '서울 마포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('홍익대학교 서울 종로 (본교)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경성대학교 부산캠퍼스 (본교)', '부산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고신대학교 영도캠퍼스 (본교)', '부산 영도', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고신대학교 부산 서구 (본교)', '부산 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동명대학교 부산캠퍼스 (본교)', '부산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동서대학교 주례캠퍼스 (본교)', '부산 사상', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동서대학교 부산 해운대 (이원화캠퍼스)', '부산 해운대', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동서대학교 부산 부산진 (이원화캠퍼스)', '부산 부산진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동아대학교 승학캠퍼스 (본교)', '부산 사하', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동아대학교 부산 서구 (이원화캠퍼스)', '부산 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동아대학교 부산 서구 (이원화캠퍼스)', '부산 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동의대학교 가야캠퍼스 (본교)', '부산 부산진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동의대학교 부산 부산진 (이원화캠퍼스)', '부산 부산진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부경대학교 대연캠퍼스 (본교)', '부산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부경대학교 부산 남구 (이원화캠퍼스)', '부산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산대학교 부산캠퍼스 (본교)', '부산 금정', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산대학교 부산 서구 (이원화캠퍼스)', '부산 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산외국어대학교 부산캠퍼스 (본교)', '부산 금정', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신라대학교 백양캠퍼스 (본교)', '부산 사상', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영산대학교 해운대캠퍼스 (본교)', '부산 해운대', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인제대학교 부산캠퍼스 (본교)', '부산 부산진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국해양대학교 아치캠퍼스 (본교)', '부산 영도', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국해양대학교 부산 영도 (이원화캠퍼스)', '부산 영도', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국해양대학교 부산 강서 (이원화캠퍼스)', '부산 강서', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국해양대학교 부산 동구 (이원화캠퍼스)', '부산 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국해양대학교 경남 창원 (이원화캠퍼스)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북대학교 대구캠퍼스 (본교)', '대구 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('계명대학교 성서캠퍼스 (본교)', '대구 달서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구가톨릭대학교 루가캠퍼스 (이원화캠퍼스)', '대구 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구가톨릭대학교 대구 중구 (이원화캠퍼스)', '대구 중구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구대학교 대명동캠퍼스 (이원화캠퍼스)', '대구 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영남대학교 대구캠퍼스 (이원화캠퍼스)', '대구 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가천대학교 메디컬캠퍼스 (이원화캠퍼스)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('안양대학교 강화캠퍼스 (이원화캠퍼스)', '인천 강화', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연세대학교 국제캠퍼스 (이원화캠퍼스)', '인천 송도', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천대학교 송도캠퍼스 (본교)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천대학교 인천 연수구 (이원화캠퍼스)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천대학교 인천 미추홀구 (이원화캠퍼스)', '인천 미추홀구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인하대학교 용현캠퍼스 (본교)', '인천 미추홀구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인하대학교 인천 연수구 (이원화캠퍼스)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인하대학교 인천 연수구 (이원화캠퍼스)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청운대학교 인천캠퍼스 (이원화캠퍼스)', '인천 미추홀구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광신대학교 광주캠퍼스 (본교)', '광주 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광주대학교 광주캠퍼스 (본교)', '광주 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('남부대학교 광주캠퍼스 (본교)', '광주 광산구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('송원대학교 광주캠퍼스 (본교)', '광주 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 용봉캠퍼스 (본교)', '광주 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 광주 동구 (이원화캠퍼스)', '광주 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('조선대학교 광주캠퍼스 (본교)', '광주 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호남대학교 광주캠퍼스 (본교)', '광주 광산구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('건양대학교 메디컬캠퍼스 (본교)', '대전 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대전대학교 대전캠퍼스 (본교)', '대전 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목원대학교 대전캠퍼스 (본교)', '대전 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('배재대학교 대전캠퍼스 (본교)', '대전 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('우송대학교 서캠퍼스 (본교)', '대전 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('을지대학교 대전캠퍼스 (본교)', '대전 중구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충남대학교 대덕캠퍼스 (본교)', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충남대학교 대전 중구 (이원화캠퍼스)', '대전 중구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한남대학교 오정동캠퍼스 (본교)', '대전 대덕구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한남대학교 대전 대덕구 (이원화캠퍼스)', '대전 대덕구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한남대학교 대전 유성구 (이원화캠퍼스)', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한밭대학교 대전캠퍼스 (본교)', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('울산대학교 메인캠퍼스 (본교)', '울산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('울산대학교 울산 남구 (이원화캠퍼스)', '울산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고려대학교 세종캠퍼스 세종캠퍼스 (분교)', '세종 조치원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('홍익대학교 세종캠퍼스 (이원화캠퍼스)', '세종 조치원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가천대학교 글로벌캠퍼스 (이원화캠퍼스)', '경기 성남', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭대학교 성심교정 (이원화캠퍼스[1])', '경기 부천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강남대학교 용인캠퍼스 (본교)', '경기 용인', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경기대학교 수원캠퍼스 (본교)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경동대학교 메트로폴캠퍼스 (이원화캠퍼스)', '경기 양주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경희대학교 국제캠퍼스 (이원화캠퍼스)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('단국대학교 죽전캠퍼스 (본교)', '경기 죽전', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대진대학교 포천캠퍼스 (본교)', '경기 포천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동국대학교 바이오메디캠퍼스 (이원화캠퍼스)', '경기 고양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('명지대학교 자연캠퍼스 (이원화캠퍼스)', '경기 용인', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성균관대학교 자연과학캠퍼스 (이원화캠퍼스)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원대학교 화성캠퍼스 (본교)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신경대학교 화성캠퍼스 (본교)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신한대학교 제1캠퍼스 (본교)', '경기 의정부', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신한대학교 경기 동두천 (이원화캠퍼스)', '경기 동두천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('아주대학교 수원캠퍼스 (본교)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('안양대학교 안양캠퍼스 (본교)', '경기 안양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('용인대학교 용인캠퍼스 (본교)', '경기 용인', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('을지대학교 성남캠퍼스 (이원화캠퍼스)', '경기 성남', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('을지대학교 경기 의정부 (이원화캠퍼스)', '경기 의정부', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중부대학교 고양캠퍼스 (이원화캠퍼스)', '경기 고양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중앙대학교 다빈치캠퍼스 (이원화캠퍼스)', '경기 안성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('평택대학교 평택캠퍼스 (본교)', '경기 평택', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한경국립대학교 안성캠퍼스 (본교)', '경기 안성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한경국립대학교 경기 평택 (이원화캠퍼스)', '경기 평택', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국공학대학교 제1캠퍼스 (본교)', '경기 시흥', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국교통대학교 의왕캠퍼스 (이원화캠퍼스)', '경기 의왕', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국외국어대학교 글로벌캠퍼스 (이원화캠퍼스)', '경기 용인', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국항공대학교 고양캠퍼스 (본교)', '경기 고양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한세대학교 군포캠퍼스 (본교)', '경기 군포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한신대학교 경기캠퍼스 (본교)', '경기 오산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한양대학교 ERICA캠퍼스 ERICA캠퍼스 (분교)', '경기 안산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('협성대학교 화성캠퍼스 (본교)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭관동대학교 강릉캠퍼스 (본교)', '강원 강릉', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강릉원주대학교 강릉캠퍼스 (본교)', '강원 강릉', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강릉원주대학교 강원 원주 (이원화캠퍼스)', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강원대학교 춘천캠퍼스 (본교)', '강원 춘천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강원대학교 강원 삼척 (이원화캠퍼스)', '강원 삼척', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강원대학교 강원 삼척 (이원화캠퍼스)', '강원 삼척', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경동대학교 글로벌캠퍼스 (이원화캠퍼스)', '강원 고성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경동대학교 강원 원주 (이원화캠퍼스)', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('상지대학교 원주캠퍼스 (본교)', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울대학교 평창캠퍼스 (이원화캠퍼스)', '강원 평창', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연세대학교 미래캠퍼스[2] 매지캠퍼스 (이원화캠퍼스[미래캠퍼스])', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연세대학교 미래캠퍼스[2] 강원 원주 (이원화캠퍼스[미래캠퍼스])', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한라대학교 원주캠퍼스 (본교)', '강원 원주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한림대학교 춘천캠퍼스 (본교)', '강원 춘천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('건국대학교 GLOCAL캠퍼스 GLOCAL캠퍼스 (분교)', '충북 충주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('극동대학교 음성캠퍼스 (본교)', '충북 음성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서원대학교 청주캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('세명대학교 제천캠퍼스 (본교)', '충북 제천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('우석대학교 진천캠퍼스 (이원화캠퍼스)', '충북 진천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('유원대학교 영동캠퍼스 (본교)', '충북 영동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중원대학교 메인캠퍼스 (본교)', '충북 괴산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청주대학교 제1캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청주대학교 충북 청주 (이원화캠퍼스)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청주대학교 충북 청주 (이원화캠퍼스)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충북대학교 개신캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충북대학교 충북 청주 (이원화캠퍼스)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충북대학교 충북 청주 (이원화캠퍼스)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국교통대학교 충주캠퍼스 (본교)', '충북 충주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국교통대학교 충북 증평 (이원화캠퍼스)', '충북 증평', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('건양대학교 창의융합캠퍼스 (이원화캠퍼스)', '충남 논산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고신대학교 천안캠퍼스 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('공주대학교 신관캠퍼스 (본교)', '충남 공주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('공주대학교 충남 공주 (이원화캠퍼스)', '충남 공주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('공주대학교 충남 천안 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('공주대학교 충남 예산 (이원화캠퍼스)', '충남 예산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('나사렛대학교 천안캠퍼스 (본교)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('남서울대학교 천안캠퍼스 (본교)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('단국대학교 천안캠퍼스 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('백석대학교 천안캠퍼스 (본교)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('상명대학교 천안캠퍼스 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('선문대학교 아산캠퍼스 (본교)', '충남 아산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('세한대학교 당진캠퍼스 (이원화캠퍼스)', '충남 당진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('순천향대학교 아산캠퍼스 (본교)', '충남 아산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('순천향대학교 충남 천안 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('유원대학교 아산캠퍼스 (이원화캠퍼스)', '충남 아산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중부대학교 충청캠퍼스 (본교)', '충남 금산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청운대학교 홍성캠퍼스 (본교)', '충남 홍성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한서대학교 서산캠퍼스 (본교)', '충남 서산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한서대학교 충남 태안 (이원화캠퍼스)', '충남 태안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호서대학교 아산캠퍼스 (본교)', '충남 아산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호서대학교 충남 천안 (이원화캠퍼스)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호서대학교 충남 당진 (이원화캠퍼스)', '충남 당진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('군산대학교 미룡캠퍼스 (본교)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('군산대학교 전북 군산 (이원화캠퍼스)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('우석대학교 전주캠퍼스 (본교)', '전북 완주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('우석대학교 전북 전주 (이원화캠퍼스)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('원광대학교 익산캠퍼스 (본교)', '전북 익산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전주캠퍼스 (본교)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 익산 (이원화캠퍼스)', '전북 익산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 고창 (이원화캠퍼스)', '전북 고창', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 군산 (이원화캠퍼스)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 완주 (이원화캠퍼스)', '전북 완주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 완주 (이원화캠퍼스)', '전북 완주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북대학교 전북 정읍 (이원화캠퍼스)', '전북 정읍', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전주대학교 전주캠퍼스 (본교)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전주대학교 전북 전주 (이원화캠퍼스)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전주대학교 전북 김제 (이원화캠퍼스)', '전북 김제', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호원대학교 군산캠퍼스 (본교)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동신대학교 나주캠퍼스 (본교)', '전남 나주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포해양대학교 목포캠퍼스 (본교)', '전남 목포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포대학교 도림캠퍼스 (본교)', '전남 무안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포대학교 전남 목포 (이원화캠퍼스)', '전남 목포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포대학교 전남 무안 (이원화캠퍼스)', '전남 무안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포대학교 전남 영암 (이원화캠퍼스)', '전남 영암', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('세한대학교 영암캠퍼스 (본교)', '전남 영암', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('순천대학교 순천캠퍼스 (본교)', '전남 순천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 둔덕캠퍼스 (이원화캠퍼스)', '전남 여수', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 전남 여수 (이원화캠퍼스)', '전남 여수', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 전남 여수 (이원화캠퍼스)', '전남 여수', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남대학교 전남 화순 (이원화캠퍼스)', '전남 화순', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('초당대학교 무안캠퍼스 (본교)', '전남 무안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북대학교 상주캠퍼스 (이원화캠퍼스)', '경북 상주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북대학교 경북 군위 (이원화캠퍼스)', '경북 군위', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경운대학교 구미캠퍼스 (본교)', '경북 구미', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경일대학교 경산캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('금오공과대학교 구미캠퍼스 (본교)', '경북 구미', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('김천대학교 김천캠퍼스 (본교)', '경북 김천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구가톨릭대학교 효성캠퍼스 (이원화캠퍼스)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구한의대학교 삼성캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구한의대학교 경북 경산 (이원화캠퍼스)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동국대학교 WISE캠퍼스 WISE캠퍼스 (분교)', '경북 경주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동양대학교 영주캠퍼스 (본교)', '경북 영주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('안동대학교 안동캠퍼스 (본교)', '경북 안동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영남대학교 경산캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('포항공과대학교 포항캠퍼스 (본교)', '경북 포항', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한동대학교 포항캠퍼스 (본교)', '경북 포항', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가야대학교 김해캠퍼스 (본교)', '경남 김해', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경남대학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경남대학교 경남 창원 (이원화캠퍼스)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경상국립대학교 가좌캠퍼스 (이원화캠퍼스)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경상국립대학교 경남 진주 (본교)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경상국립대학교 경남 통영 (이원화캠퍼스)', '경남 통영', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경상국립대학교 경남 창원 (이원화캠퍼스)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경상국립대학교 경남 진주 (이원화캠퍼스)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산대학교 양산캠퍼스 (이원화캠퍼스)', '경남 양산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산대학교 경남 밀양 (이원화캠퍼스)', '경남 밀양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산장신대학교 김해캠퍼스 (본교)', '경남 김해', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영산대학교 양산캠퍼스 (본교)', '경남 양산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인제대학교 김해캠퍼스 (본교)', '경남 김해', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('창신대학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('창원대학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국국제대학교 진주캠퍼스 (본교)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('제주국제대학교 제주캠퍼스 (본교)', '제주특별자치도 제주시', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('제주대학교 아라캠퍼스 (본교)', '제주특별자치도 제주시', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('제주대학교 제주특별자치도 제주시 (이원화캠퍼스)', '제주특별자치도 제주시', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('국방대학교 논산캠퍼스 (본교)', '충남 논산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('국방대학교 서울 용산 (이원화캠퍼스)', '서울 용산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('육군사관학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('육군3사관학교 영천캠퍼스 (본교)', '경북 영천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('공군사관학교 청주캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('해군사관학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('국군간호사관학교 대전캠퍼스 (본교)', '대전 유성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경찰대학 아산캠퍼스 (본교)', '충남 아산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국농수산대학 전주캠퍼스 (본교)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국전통문화대학교 부여캠퍼스 (본교)', '충남 부여', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('GIST 광주캠퍼스', '광주 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('DGIST 대구캠퍼스', '대구 달성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('UNIST 울산캠퍼스', '울산 울주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('KAIST 본원 (본원)', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('KAIST 대전 유성구 ()', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('KAIST 서울 동대문구 ()', '서울 동대문구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('KAIST 서울 강남구 ()', '서울 강남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('덕성여자대학교 쌍문동캠퍼스 (본교)', '서울 도봉', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('덕성여자대학교 서울 종로 (이원화캠퍼스)', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동덕여자대학교 서울캠퍼스 (본교)', '서울 강북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울여자대학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성신여자대학교 수정캠퍼스 (본교)', '서울 성북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성신여자대학교 서울 강북 (이원화캠퍼스)', '서울 강북', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('숙명여자대학교 서울캠퍼스 (본교)', '서울 용산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('이화여자대학교 대현캠퍼스 (본교)', '서울 서대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('이화여자대학교 서울 강서 (이원화캠퍼스)', '서울 강서', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광주여자대학교 광주캠퍼스 (본교)', '광주 광산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('감리교신학대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울기독대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('장로회신학대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국성서대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울한영대학교', '서울', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천가톨릭대학교', '인천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대전신학대학교', '대전', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('침례신학대학교', '대전', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산가톨릭대학교', '부산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고신대학교', '부산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('루터대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울신학대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울장신대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성결대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원가톨릭대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('아세아연합신학대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('중앙승가대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('칼빈대학교', '경기', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동양미래대학교 서울캠퍼스 (본교)', '서울 구로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('명지전문대학 서울캠퍼스 (본교)', '서울 서대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('삼육보건대학교 서울캠퍼스 (본교)', '서울 동대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서일대학교 서울캠퍼스 (본교)', '서울 중랑', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인덕대학교 서울캠퍼스 (본교)', '서울 노원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국영상대학교 세종캠퍼스 (본교)', '세종 장군', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인하공업전문대학 인천캠퍼스 (본교)', '인천 미추홀', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천재능대학교 송림캠퍼스 (본교)', '인천 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('인천재능대학교 인천 연수구 (이원화캠퍼스)', '인천 연수구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('울산과학대학교 서부캠퍼스 (본교)', '울산 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('울산과학대학교 울산 동구 (이원화캠퍼스)', '울산 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('춘해보건대학교 울주캠퍼스 (본교)', '울산 울주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광주보건대학교 광주캠퍼스 (본교)', '광주 광산구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('기독간호대학교 광주캠퍼스 (본교)', '광주 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동강대학교 광주캠퍼스 (본교)', '광주 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서영대학교 광주캠퍼스 (본교)', '광주 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서영대학교 경기 파주 (이원화캠퍼스)', '경기 파주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('조선간호대학교 광주캠퍼스 (본교)', '광주 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('조선이공대학교 광주캠퍼스 (본교)', '광주 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('계명문화대학교 대구캠퍼스 (본교)', '대구 달서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구공업대학교 대구캠퍼스 (본교)', '대구 달서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구과학대학교 대구캠퍼스 (본교)', '대구 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대구보건대학교 대구캠퍼스 (본교)', '대구 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수성대학교 대구캠퍼스 (본교)', '대구 수성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영남이공대학교 대구캠퍼스 (본교)', '대구 남구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영진전문대학교 복현캠퍼스 (본교)', '대구 북구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대덕대학교 대전캠퍼스 (본교)', '대전 유성구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대전과학기술대학교 대전캠퍼스 (본교)', '대전 서구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대전보건대학교 대전캠퍼스 (본교)', '대전 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('우송정보대학 대전캠퍼스 (본교)', '대전 동구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경기과학기술대학교 시흥캠퍼스 (본교)', '경기 시흥', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경민대학교 의정부캠퍼스 (본교)', '경기 의정부', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경복대학교 남양주캠퍼스 (본교)', '경기 남양주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경복대학교 경기 포천 (이원화캠퍼스)', '경기 포천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('계원예술대학교 의왕캠퍼스 (본교)', '경기 의왕', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('국제대학교 평택캠퍼스 (본교)', '경기 평택', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('김포대학교 김포캠퍼스 (본교)', '경기 김포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('농협대학교 고양캠퍼스 (본교)', '경기 고양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대림대학교 안양캠퍼스 (본교)', '경기 안양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동남보건대학교 수원캠퍼스 (본교)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동서울대학교 성남캠퍼스 (본교)', '경기 성남', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동아방송예술대학교 안성캠퍼스 (본교)', '경기 안성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동원대학교 광주캠퍼스 (본교)', '경기 광주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('두원공과대학교 안성캠퍼스 (본교)', '경기 안성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('두원공과대학교 경기 파주 (이원화캠퍼스)', '경기 파주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부천대학교 부천캠퍼스 (본교)', '경기 부천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서영대학교 파주캠퍼스 (이원화캠퍼스)', '경기 파주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울예술대학교 안산캠퍼스 (본교)', '경기 안성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서정대학교 양주캠퍼스 (본교)', '경기 양주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원과학대학교 화성캠퍼스 (본교)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원여자대학교 수원캠퍼스 (본교)', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원여자대학교 경기 화성 (이원화캠퍼스)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신구대학교 성남캠퍼스 (본교)', '경기 성남', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신안산대학교 안산캠퍼스 (본교)', '경기 안산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('안산대학교 안산캠퍼스 (본교)', '경기 안산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연성대학교 안양캠퍼스 (본교)', '경기 안양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('여주대학교 여주캠퍼스 (본교)', '경기 여주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('오산대학교 오산캠퍼스 (본교)', '경기 오산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('용인송담대학교 용인캠퍼스 (본교)', '경기 용인', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('웅지세무대학교 파주캠퍼스 (본교)', '경기 파주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('유한대학교 부천캠퍼스 (본교)', '경기 부천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('장안대학교 화성캠퍼스 (본교)', '경기 화성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청강문화산업대학교 이천캠퍼스 (본교)', '경기 이천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국관광대학교 이천캠퍼스 (본교)', '경기 이천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강릉영동대학교 강릉캠퍼스 (본교)', '강원 강릉', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강원관광대학교 태백캠퍼스 (본교)', '강원 태백', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강원도립대학교 강릉캠퍼스 (본교)', '강원 강릉', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('세경대학교 영월캠퍼스 (본교)', '강원 영월', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('송곡대학교 춘천캠퍼스 (본교)', '강원 춘천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('송호대학교 횡성캠퍼스 (본교)', '강원 횡성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국골프대학교 횡성캠퍼스 (본교)', '강원 횡성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한림성심대학교 춘천캠퍼스 (본교)', '강원 춘천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('강동대학교 음성캠퍼스 (본교)', '충북 음성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대원대학교 제천캠퍼스 (본교)', '충북 제천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충북도립대학교 옥천캠퍼스 (본교)', '충북 옥천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충북보건과학대학교 청주캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충청대학교 청주캠퍼스 (본교)', '충북 청주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('백석문화대학교 천안캠퍼스 (본교)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('신성대학교 당진캠퍼스 (본교)', '충남 당진', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('아주자동차대학 보령캠퍼스 (본교)', '충남 보령', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연암대학교 천안캠퍼스 (본교)', '충남 천안', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('충남도립대학교 청양캠퍼스 (본교)', '충남 청양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('혜전대학교 홍성캠퍼스 (본교)', '충남 홍성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('군산간호대학교 군산캠퍼스 (본교)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('군장대학교 군산캠퍼스 (본교)', '전북 군산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('백제예술대학교 완주캠퍼스 (본교)', '전북 완주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('원광보건대학교 익산캠퍼스 (본교)', '전북 익산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전북과학대학교 정읍캠퍼스 (본교)', '전북 정읍', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전주기전대학 전주캠퍼스 (본교)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전주비전대학교 전주캠퍼스 (본교)', '전북 전주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('고구려대학교 나주캠퍼스 (본교)', '전남 나주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('광양보건대학교 광양캠퍼스 (본교)', '전남 광양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동아보건대학교 영암캠퍼스 (본교)', '전남 영암', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('목포과학대학교 목포캠퍼스 (본교)', '전남 목포', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('순천제일대학교 덕월캠퍼스 (본교)', '전남 순천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('순천제일대학교 전남 순천 (이원화캠퍼스)', '전남 순천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남과학대학교 곡성캠퍼스 (본교)', '전남 곡성', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('전남도립대학교 담양캠퍼스 (본교)', '전남 담양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('청암대학교 순천캠퍼스 (본교)', '전남 순천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한영대학교 여수캠퍼스 (본교)', '전남 여수', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('가톨릭상지대학교 안동캠퍼스 (본교)', '경북 안동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북과학대학교 칠곡캠퍼스 (본교)', '경북 칠곡', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북도립대학교 예천캠퍼스 (본교)', '경북 예천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경북전문대학교 영주캠퍼스 (본교)', '경북 영주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('구미대학교 구미캠퍼스 (본교)', '경북 구미', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대경대학교 메인캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('대경대학교 경기 남양주 (이원화캠퍼스)', '경기 남양주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('문경대학교 문경캠퍼스 (본교)', '경북 문경', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서라벌대학교 경주캠퍼스 (본교)', '경북 경주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('선린대학교 포항캠퍼스 (본교)', '경북 포항', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('성운대학교 영천캠퍼스 (본교)', '경북 영천', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('안동과학대학교 안동캠퍼스 (본교)', '경북 안동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영남외국어대학 경산캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('영진전문대학교 글로벌캠퍼스 (이원화캠퍼스)', '경북 칠곡', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('포항대학교 포항캠퍼스 (본교)', '경북 포항', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('호산대학교 경산캠퍼스 (본교)', '경북 경산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('거제대학교 거제캠퍼스 (본교)', '경남 거제', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경남도립거창대학 거창캠퍼스 (본교)', '경남 거창', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경남도립남해대학 남해캠퍼스 (본교)', '경남 남해', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('김해대학교 김해캠퍼스 (본교)', '경남 김해', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('마산대학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('동원과학기술대학교 양산캠퍼스 (본교)', '경남 양산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('연암공과대학교 진주캠퍼스 (본교)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('진주보건대학교 진주캠퍼스 (본교)', '경남 진주', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('창원문성대학교 창원캠퍼스 (본교)', '경남 창원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국승강기대학교 거창캠퍼스 (본교)', '경남 거창', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('제주관광대학교 제주캠퍼스 (본교)', '제주특별자치도 제주시', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('제주한라대학교 제주캠퍼스 (본교)', '제주특별자치도 제주시', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('경인여자대학교', '인천 계양', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('배화여자대학교', '서울 종로', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('부산여자대학교', '부산 진구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('서울여자간호대학교', '서울 서대문', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('수원여자대학교', '경기 수원', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('숭의여자대학교', '서울 중구', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한양여자대학교', '서울 성동', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국폴리텍Ⅰ대학 서울정수캠퍼스 (구 서울정수기능대학)', '서울 용산', NOW(), NOW());
INSERT INTO University (`name`, `address`, `created_at`, `updated_at`) VALUES ('한국폴리텍Ⅰ대학 서울 강서 (구 서울정보기능대학)', '서울 강서', NOW(), NOW());
