name: Production Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: umc-hustle-deploy
  AWS_CODE_DEPLOY_APPLICATION: hustle-code-deploy
  AWS_CODE_DEPLOY_GROUP: production

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}

      - name: Make directory for deployment
        run: mkdir deploy
          
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Make zip file
        run: zip ./$GITHUB_SHA.zip build/libs/*.jar appspec.yml
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$AWS_S3_BUCKET/$GITHUB_SHA.zip

      - name: Deploy to EC2 through CodeDeploy
        run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=$GITHUB_SHA.zip,bundleType=zip

      - name: Discord notifications when failed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: "${{ secrets.CICD_DISCORD_WEBHOOK_URL }}/github"
          username: "Hustle Deployment"
          content: "[허슬 서버 배포 실패 알림] ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if: failure()
